# prepare.yml の実行対象のホストをここに書く。
# 新しいホストを準備するときはまずここに書いてから prepare.yml を実行する。
#preparing_servers:


# prepare.yml が完了したら、ここに移動する。
running_servers:
  hosts:
    bgprt1:
      running_ssh_host: 10.253.33.1
      fqdn_hostname: bgprt1.example.org

    bgprt2:
      running_ssh_host: 10.253.33.2
      fqdn_hostname: bgprt2.example.org


# 古いサーバーで実行の対象としないものは、ここに移動する。
dead_servers:


