# prepare.yml の実行対象のホストをここに書く。
# 新しいホストを準備するときはまずここに書いてから prepare.yml を実行する。
#preparing_servers:


# prepare.yml が完了したら、ここに移動する。
running_servers:
  hosts:
    crossvm1:
      running_ssh_host: 10.21.1.56
      prepare_temp_ssh_host: 10.21.100.9
      fqdn_hostname: crossvm1.sec.softether.co.jp


# 古いサーバーで実行の対象としないものは、ここに移動する。
dead_servers:
  hosts:
    test1:
      running_ssh_host: 10.20.30.40
      prepare_temp_ssh_host: 10.20.100.83
      fqdn_hostname: test1.sec.softether.co.jp


