# IPA Easy BGP Starter Kit
# Copyright (c) 2014-2019 Daiyuu Nobori
# Copyright (c) 2020 IPA CyberLab
# All rights reserved.
# 
# 本 Easy BGP Starter Kit は無償・無保証で提供されるものであり、製作者等は一切の責任を負わない。
# セキュリティや品質などの一切の保証はない。
# ユーザーの各自の責任で使用すること。

# 本ファイルの説明:
# 共通設定ファイルである。

ansible_ssh_host: "{{ running_ssh_host }}"

domain_suffix: example.org
resolv_conf_contents: |
  domain example.org
  nameserver 8.8.8.8
  nameserver 8.8.4.4
enable_ipv4_forward: false
enable_ipv6_forward: false
disable_ipv6_all: false
network_boottime_1:
network_boottime_2:
network_static_routes:
network_iptables_rules:
disable_ntp: false
disable_local_nic_ipif_after_lxd_install: false
skip_common_linux: false
skip_lxd_install: false
#ansible_become_pass: "{{ my_user_password }}"
lxd_container_config_timeout: 60


# TODO: syslog を送付する場合は、syslog サーバーの IPv4 アドレスに置換すること。
# syslog サーバーは、MGMT セグメント内にあっても、グローバル IPv4 アドレスであっても良いのである。
syslog_server: 1.2.3.4
